name: 'Label Commenter'
description: 'This action is one of label triggered GitHub Actions for posting a template message. After commenting, it can automatically close or reopen issues. Of course, it also can manage pull requests.'
author: 'peaceiris'
inputs:
  github_token:
    description: 'Auth token used to manage issues or pull requests'
    required: true
  config_file:
    description: 'Path to action setting file'
    default: '.github/label-commenter-config.yml'
    required: false
runs:
  using: 'node12'
  main: 'lib/index.js'
branding:
  icon: 'tag'
  color: 'orange'
