name: User Support
about: Questions about this action
title: 'sample_title'
labels: support
assignees: peaceiris
body:
  - type: markdown
    attributes:
      value: |
        Please note we will close your issue without comment if you do not fill out the issue checklist below and provide ALL the requested information.
        If you repeatedly fail to use the issue template, we will block you from ever submitting issues to this repository again.
  - type: checkboxes
    attributes:
      description: Checklist before creating an issue.
      options:
        - label: "I am using the latest version of this aciton."
          required: true
        - label: "I have read the latest README and followed the instructions."
          required: true
        - label: "I have read the latest GitHub Actions official documentation and learned the basic spec and concepts."
          required: true
  - type: textarea
    attributes:
      description: A clear and concise description of what the question is.
      render: markdown
    validations:
      required: false
  - type: textarea
    attributes:
      description: Links to your public repository, YAML config file, and YAML workflow file.
      render: markdown
      value: |
        Public repository:
        YAML config:
        YAML workflow:
    validations:
      required: false
  - type: textarea
    attributes:
      description: Relevant log output.
      placeholder: Copy and paste any relevant log output here. This will be automatically formatted into code, so no need for backticks.
      render: txt
    validations:
      required: false
  - type: textarea
    attributes:
      description: Additional context.
      placeholder: Write any other context about the question here.
      render: markdown
    validations:
      required: false
