blank_issues_enabled: false
contact_links:
  - name: GitHub Actions - GitHub Support Community Forum
    url: https://github.community/c/github-actions/41
    about: Please ask questions about GitHub Actions here.
