name: Commenter

on:
  issues:
    types:
      - labeled
      - unlabeled
  pull_request:
    types:
      - labeled
      - unlabeled

jobs:
  comment:
    runs-on: ubuntu-18.04
    steps:
      - name: Commenter
        uses: peaceiris/actions-label-commenter@v0.1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
