name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: peaceiris/workflows/create-release-npm@v0.16.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
